from environs import Env

env = Env()
env.read_env()

SERVER_CACHE_STORE_URL = env.str("SERVER_CACHE_STORE_URL", None)
SERVER_CACHE_EXPIRE_SECONDS = env.int("SERVER_CACHE_EXPIRE_SECONDS", 120)
SERVER_CACHE_SEARCH_EXPIRE_SECONDS = env.int("SERVER_CACHE_SEARCH_EXPIRE_SECONDS", SERVER_CACHE_EXPIRE_SECONDS)
SERVER_CACHE_IFRAMES_EXPIRE_SECONDS = env.int("SERVER_CACHE_IFRAMES_EXPIRE_SECONDS", SERVER_CACHE_EXPIRE_SECONDS)

APICOLLAPS_TOKEN = env.str("APICOLLAPS_TOKEN", "token")
VIDEOCDN_TOKEN = env.str("VIDEOCDN_TOKEN", "token")
APIVB_TOKEN = env.str("APIVB_TOKEN", "token")
BAZON_TOKEN = env.str("BAZON_TOKEN", "token")
ALOHA_TOKEN = env.str("ALOHA_TOKEN", "token")
