name: Purge cache

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to purge")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Purge completed!")
